#!/bin/sh

DIR_PATH=`dirname $0`
cd $DIR_PATH/..

######################################################
# Combine files when new translations have been made #
###################################################### 
echo "***adding the new translations to the .strings files***"
for file in `ls English.lproj/*.xib | sed -e "s:English.lproj/::g" | sed -e "s:.xib::g"`
do
  wincent-strings-util --base French.lproj/$file.strings --combine French.lproj/$file.new.strings  --output French.lproj/$file.strings
done

wincent-strings-util --base French.lproj/Localizable.strings --combine French.lproj/Localizable.new.strings  --output French.lproj/Localizable.strings
echo ""
echo "***You can now execute the script generate-french-xib-window***"
